version: '3.6'
services:
  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

  elasticsearch2:
    # image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana.elastic.io
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - esnet


volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
