version: '3.6'

services:
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana.elastic.io
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
   
networks:
  default:
    external:
      name: docker_esnet
