version: '3.4'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - /home/dougdev/developer/docker/databases/redis:/data
      - /home/dougdev/developer/docker/config/redis/redis.conf:/usr/local/etc/redis/redis.conf